[package]
name = "sellnftbug-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.sellnftbug]
path = ".."

[dependencies.multiversx-sc]
version = "0.39.5"

[dependencies.multiversx-sc-meta]
version = "0.39.5"